-- Bronze DDL for source 'ird' — 1 tables
-- Generated by gen_bronze_ddl.py · review before applying · money widened to Decimal(38,s)

-- ird.taxpayer (1,234,567 rows)
CREATE TABLE IF NOT EXISTS `bronze`.`ird__taxpayer`
(
    `tax_serial` Int64,
    `tax_name` Nullable(String),
    `tax_segment` Nullable(String),
    `tax_balance` Nullable(Decimal(38, 2)),
    `tax_assessment` Nullable(Decimal(38, 2)),
    `_extracted_at` DateTime64(3),
    `_batch_id` String,
    `_source` LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(`_extracted_at`)
ORDER BY (`tax_serial`);

