#!/usr/bin/env python3
"""
gen_bronze_ddl.py — source schema spec -> ClickHouse Bronze DDL (MTCA conventions).

Reads a schema spec (JSON, produced by `profile_source.py --emit-schema` or hand-built) and
emits repo-convention ClickHouse Bronze DDL: MergeTree, meta columns, PARTITION BY month,
ORDER BY the key, and — critically — **money/decimal widened to Decimal(38, s), never 18**
(real pre-prod values overflow Decimal(18,4); this caused a real incident on the sister project).

Offline and deterministic (pure standard library) so it can be reviewed and tested without a
database. The DDL is a draft for human review before `dbt run` / apply.

Schema spec format (JSON):
{
  "source": "ird",
  "tables": {
    "taxpayer": {
      "row_count": 12345,
      "primary_key": ["tax_serial"],
      "columns": [
        {"name": "tax_serial",  "type": "serial",        "nullable": false},
        {"name": "tax_name",    "type": "varchar(120)",   "nullable": true},
        {"name": "tax_balance", "type": "decimal(16,2)",  "nullable": true},
        {"name": "tax_regdate", "type": "date",           "nullable": true}
      ]
    }
  }
}

Usage:
  python gen_bronze_ddl.py --schema <spec.json> [--out <dir>] [--database bronze]
"""
import argparse, json, os, re, sys

META_COLUMNS = [
    ("_extracted_at", "DateTime64(3)"),   # when this row was pulled
    ("_batch_id",     "String"),          # reconciliation unit (per-load)
    ("_source",       "LowCardinality(String)"),
]

def map_type(src_type: str):
    """Map an Informix/SQL source type to a ClickHouse type. Money/decimal -> Decimal(38,s)."""
    t = src_type.strip().lower()
    # decimal / numeric / money -> WIDEN to Decimal(38, scale). Never 18.
    m = re.search(r'(?:decimal|numeric)\s*\(\s*\d+\s*,\s*(\d+)\s*\)', t)
    if m:
        return f"Decimal(38, {int(m.group(1))})"
    if t.startswith("decimal") or t.startswith("numeric") or "money" in t:
        return "Decimal(38, 4)"                      # unspecified scale -> safe 4
    if "serial" in t or t in ("int8", "bigint"):
        return "Int64"
    if t.startswith("int") or t == "integer":
        return "Int32"
    if "smallint" in t:
        return "Int16"
    if "smallfloat" in t or t == "real":
        return "Float32"
    if "float" in t or "double" in t:
        return "Float64"
    if t.startswith("date") and "time" not in t:
        return "Date32"
    if "datetime" in t or "timestamp" in t:
        return "DateTime64(3)"
    if any(t.startswith(p) for p in ("char", "varchar", "nchar", "nvarchar", "lvarchar", "text", "string", "clob")):
        return "String"
    if "bool" in t:
        return "Bool"
    return "String"                                  # unknown -> String, never silently drop

def col_ddl(c):
    ch = map_type(c["type"])
    if c.get("nullable", True):
        ch = f"Nullable({ch})"
    return f"    `{c['name']}` {ch}"

def table_ddl(database, source, table, spec):
    cols = [col_ddl(c) for c in spec["columns"]]
    cols += [f"    `{n}` {t}" for n, t in META_COLUMNS]
    pk = spec.get("primary_key") or []
    order = "(" + ", ".join(f"`{k}`" for k in pk) + ")" if pk else "tuple()"
    note = ""
    if not pk:
        note = "    -- NOTE: no primary key in source — confirm ORDER BY before production.\n"
    rc = spec.get("row_count")
    rc_note = f"  -- source row_count at profile: {rc:,}\n" if isinstance(rc, int) else ""
    return (
        f"-- {source}.{table}{(' ('+format(rc,',')+' rows)') if isinstance(rc,int) else ''}\n"
        f"CREATE TABLE IF NOT EXISTS `{database}`.`{source}__{table}`\n(\n"
        + ",\n".join(cols) + "\n)\n"
        f"ENGINE = MergeTree\n"
        f"PARTITION BY toYYYYMM(`_extracted_at`)\n"
        f"{note}ORDER BY {order};\n"
    )

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", required=True, help="schema spec JSON")
    ap.add_argument("--database", default="bronze", help="target ClickHouse database (default bronze)")
    ap.add_argument("--out", help="write one .sql file here (default: stdout)")
    args = ap.parse_args()

    spec = json.load(open(args.schema, encoding="utf-8"))
    source = spec.get("source") or os.path.splitext(os.path.basename(args.schema))[0]
    tables = spec["tables"]

    blocks = [f"-- Bronze DDL for source '{source}' — {len(tables)} tables",
              "-- Generated by gen_bronze_ddl.py · review before applying · money widened to Decimal(38,s)",
              ""]
    for t in sorted(tables):
        blocks.append(table_ddl(args.database, source, t, tables[t]))
    ddl = "\n".join(blocks) + "\n"

    if args.out:
        os.makedirs(args.out, exist_ok=True)
        # repo convention: clickhouse/0XX_bronze_<source>.sql — caller numbers it
        path = os.path.join(args.out, f"bronze_{source}.sql")
        open(path, "w", encoding="utf-8", newline="\n").write(ddl)
        print(f"wrote {path}  ({len(tables)} tables)")
    else:
        sys.stdout.write(ddl)

if __name__ == "__main__":
    main()
